package kingdom.smp.effect;

import net.minecraft.core.particles.DustParticleOptions;
import net.minecraft.core.particles.ParticleTypes;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.util.ARGB;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.phys.Vec3;

/**
 * Spell Effect: Orbiting charge-up ring then 3 fast projectile trails
 * Element: arcane
 * Layers: 4
 *
 * Generated by Particle Maker — Kingdom SMP
 */
public class ArcaneBarrageEffect {

    /**
     * Spawn the complete spell effect.
     *
     * @param level  The server level
     * @param center Center position of the effect
     * @param caster The casting entity (for direction/look vector), nullable
     * @param tick   Current tick counter (for animation phasing)
     */
    public static void spawn(ServerLevel level, Vec3 center, Entity caster, int tick) {
        if (tick <= 15) spawnLayer0(level, center, caster, tick);
        if (tick <= 15) if (tick % 2 == 0) spawnLayer1(level, center, caster, tick);
        if (tick >= 15) if (tick <= 25) spawnLayer2(level, center, caster, tick);
        if (tick >= 25) if (tick <= 28) spawnLayer3(level, center, caster, tick);
    }

    private static void spawnLayer0(ServerLevel level, Vec3 center, Entity caster, int tick) {
        var particle = new DustParticleOptions(ARGB.colorFromFloat(1f, 0.3f, 0.6f, 1f), 0.8f);
        double phase = tick * 0.15;
        for (int i = 0; i < 8; i++) {
            double angle = (2.0 * Math.PI * i / 8) + phase;
            double ox = Math.cos(angle) * 1.2;
            double oz = Math.sin(angle) * 1.2;
            level.sendParticles(particle, center.x + ox, center.y + 1.0, center.z + oz, 1, 0, 0, 0, 0);
        }
    }

    private static void spawnLayer1(ServerLevel level, Vec3 center, Entity caster, int tick) {
        var particle = ParticleTypes.ENCHANT;
        double phase = tick * 0.1;
        for (int i = 0; i < 12; i++) {
            double angle = (2.0 * Math.PI * i / 12) + phase;
            double ox = Math.cos(angle) * 0.8;
            double oz = Math.sin(angle) * 0.8;
            level.sendParticles(particle, center.x + ox, center.y, center.z + oz, 1, 0, 0, 0, 0);
        }
    }

    private static void spawnLayer2(ServerLevel level, Vec3 center, Entity caster, int tick) {
        var particle = new DustParticleOptions(ARGB.colorFromFloat(1f, 0.3f, 0.6f, 1f), 0.6f);
        // meteor_trail formation
        for (int i = 0; i < 15; i++) {
            double ox = (level.getRandom().nextDouble() - 0.5) * 2;
            double oy = level.getRandom().nextDouble() * 2;
            double oz = (level.getRandom().nextDouble() - 0.5) * 2;
            level.sendParticles(particle, center.x + ox, center.y + oy, center.z + oz, 1, 0, 0, 0, 0);
        }
    }

    private static void spawnLayer3(ServerLevel level, Vec3 center, Entity caster, int tick) {
        var particle = ParticleTypes.ENCHANTED_HIT;
        double golden = Math.PI * (3.0 - Math.sqrt(5.0));
        for (int i = 0; i < 8; i++) {
            double y = 1.0 - (2.0 * i / (8 - 1));
            double r = Math.sqrt(1.0 - y * y);
            double theta = golden * i;
            double nx = r * Math.cos(theta);
            double nz = r * Math.sin(theta);
            double ny = y;
            level.sendParticles(particle, center.x, center.y, center.z,
                0, nx * 0.15, ny * 0.15, nz * 0.15, 1.0);
        }
    }

    // ── Math helpers ─────────────────────────────────────────

    private static double[] rotateY(double x, double z, double angle) {
        double cos = Math.cos(angle);
        double sin = Math.sin(angle);
        return new double[]{ x * cos - z * sin, x * sin + z * cos };
    }

    private static Vec3 getLookDirection(Entity entity) {
        if (entity == null) return new Vec3(0, 0, 1);
        return entity.getLookAngle();
    }
}
