package kingdom.smp.effect;

import net.minecraft.core.particles.ParticleTypes;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.phys.Vec3;

/**
 * Spell Effect: Gentle ambient enchant particles floating around entity
 * Element: arcane
 * Layers: 2
 *
 * Generated by Particle Maker — Kingdom SMP
 */
public class PassiveAuraEffect {

    /**
     * Spawn the complete spell effect.
     *
     * @param level  The server level
     * @param center Center position of the effect
     * @param caster The casting entity (for direction/look vector), nullable
     * @param tick   Current tick counter (for animation phasing)
     */
    public static void spawn(ServerLevel level, Vec3 center, Entity caster, int tick) {
        if (tick <= 9999) if (tick % 4 == 0) spawnLayer0(level, center, caster, tick);
        if (tick <= 9999) if (tick % 8 == 0) spawnLayer1(level, center, caster, tick);
    }

    private static void spawnLayer0(ServerLevel level, Vec3 center, Entity caster, int tick) {
        var particle = ParticleTypes.ENCHANT;
        for (int i = 0; i < 3; i++) {
            double angle = level.getRandom().nextDouble() * 2 * Math.PI;
            double r = level.getRandom().nextDouble() * 0.8;
            double ox = Math.cos(angle) * r;
            double oz = Math.sin(angle) * r;
            double oy = level.getRandom().nextDouble() * 2.0;
            level.sendParticles(particle, center.x + ox, center.y + oy, center.z + oz,
                1, 0, 0.01, 0, 0.005);
        }
    }

    private static void spawnLayer1(ServerLevel level, Vec3 center, Entity caster, int tick) {
        var particle = ParticleTypes.WITCH;
        for (int i = 0; i < 2; i++) {
            double angle = level.getRandom().nextDouble() * 2 * Math.PI;
            double r = level.getRandom().nextDouble() * 0.6;
            double ox = Math.cos(angle) * r;
            double oz = Math.sin(angle) * r;
            double oy = level.getRandom().nextDouble() * 1.8;
            level.sendParticles(particle, center.x + ox, center.y + oy, center.z + oz,
                1, 0, 0.01, 0, 0.005);
        }
    }

    // ── Math helpers ─────────────────────────────────────────

    private static double[] rotateY(double x, double z, double angle) {
        double cos = Math.cos(angle);
        double sin = Math.sin(angle);
        return new double[]{ x * cos - z * sin, x * sin + z * cos };
    }

    private static Vec3 getLookDirection(Entity entity) {
        if (entity == null) return new Vec3(0, 0, 1);
        return entity.getLookAngle();
    }
}
