package kingdom.smp.effect;

import net.minecraft.core.particles.DustColorTransitionOptions;
import net.minecraft.core.particles.DustParticleOptions;
import net.minecraft.core.particles.ParticleTypes;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.util.ARGB;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.phys.Vec3;

/**
 * Spell Effect: Protective dome with double helix orbiting outside
 * Element: holy
 * Layers: 3
 *
 * Generated by Particle Maker — Kingdom SMP
 */
public class SoulShieldEffect {

    /**
     * Spawn the complete spell effect.
     *
     * @param level  The server level
     * @param center Center position of the effect
     * @param caster The casting entity (for direction/look vector), nullable
     * @param tick   Current tick counter (for animation phasing)
     */
    public static void spawn(ServerLevel level, Vec3 center, Entity caster, int tick) {
        if (tick <= 100) if (tick % 2 == 0) spawnLayer0(level, center, caster, tick);
        if (tick <= 100) spawnLayer1(level, center, caster, tick);
        if (tick <= 100) if (tick % 5 == 0) spawnLayer2(level, center, caster, tick);
    }

    private static void spawnLayer0(ServerLevel level, Vec3 center, Entity caster, int tick) {
        var particle = ParticleTypes.END_ROD;
        double golden = Math.PI * (3.0 - Math.sqrt(5.0));
        for (int i = 0; i < 30; i++) {
            double y = (double) i / (30 - 1);  // 0 to 1 (bottom to top)
            double r = Math.sqrt(1.0 - y * y);
            double theta = golden * i;
            double ox = r * Math.cos(theta) * 2.0;
            double oz = r * Math.sin(theta) * 2.0;
            double oy = y * 2.0;
            if (oy >= 0) {
                level.sendParticles(particle, center.x + ox, center.y + oy, center.z + oz, 1, 0, 0, 0, 0);
            }
        }
    }

    private static void spawnLayer1(ServerLevel level, Vec3 center, Entity caster, int tick) {
        var particle = new DustColorTransitionOptions(
            ARGB.color(255, 255, 204),
            ARGB.color(255, 242, 153),
            0.7f);
        // double_helix formation
        for (int i = 0; i < 24; i++) {
            double ox = (level.getRandom().nextDouble() - 0.5) * 2;
            double oy = level.getRandom().nextDouble() * 2;
            double oz = (level.getRandom().nextDouble() - 0.5) * 2;
            level.sendParticles(particle, center.x + ox, center.y + oy, center.z + oz, 1, 0, 0, 0, 0);
        }
    }

    private static void spawnLayer2(ServerLevel level, Vec3 center, Entity caster, int tick) {
        var particle = new DustParticleOptions(ARGB.color(255, 255, 204), 0.5f);
        double phase = tick * 0.1;
        for (int i = 0; i < 16; i++) {
            double angle = (2.0 * Math.PI * i / 16) + phase;
            double ox = Math.cos(angle) * 2.0;
            double oz = Math.sin(angle) * 2.0;
            level.sendParticles(particle, center.x + ox, center.y, center.z + oz, 1, 0, 0, 0, 0);
        }
    }

    // ── Math helpers ─────────────────────────────────────────

    private static double[] rotateY(double x, double z, double angle) {
        double cos = Math.cos(angle);
        double sin = Math.sin(angle);
        return new double[]{ x * cos - z * sin, x * sin + z * cos };
    }

    private static Vec3 getLookDirection(Entity entity) {
        if (entity == null) return new Vec3(0, 0, 1);
        return entity.getLookAngle();
    }
}
