package kingdom.smp.effect;

import net.minecraft.core.particles.ParticleTypes;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.phys.Vec3;

/**
 * Spell Effect: Departure explosion burst and arrival ring with portals
 * Element: void
 * Layers: 3
 *
 * Generated by Particle Maker — Kingdom SMP
 */
public class TeleportBurstEffect {

    /**
     * Spawn the complete spell effect.
     *
     * @param level  The server level
     * @param center Center position of the effect
     * @param caster The casting entity (for direction/look vector), nullable
     * @param tick   Current tick counter (for animation phasing)
     */
    public static void spawn(ServerLevel level, Vec3 center, Entity caster, int tick) {
        if (tick <= 5) spawnLayer0(level, center, caster, tick);
        if (tick <= 5) spawnLayer1(level, center, caster, tick);
        if (tick <= 10) spawnLayer2(level, center, caster, tick);
    }

    private static void spawnLayer0(ServerLevel level, Vec3 center, Entity caster, int tick) {
        var particle = ParticleTypes.PORTAL;
        double golden = Math.PI * (3.0 - Math.sqrt(5.0));
        for (int i = 0; i < 30; i++) {
            double y = 1.0 - (2.0 * i / (30 - 1));
            double r = Math.sqrt(1.0 - y * y);
            double theta = golden * i;
            double nx = r * Math.cos(theta);
            double nz = r * Math.sin(theta);
            double ny = y;
            level.sendParticles(particle, center.x, center.y, center.z,
                0, nx * 0.4, ny * 0.4, nz * 0.4, 1.0);
        }
    }

    private static void spawnLayer1(ServerLevel level, Vec3 center, Entity caster, int tick) {
        var particle = ParticleTypes.REVERSE_PORTAL;
        double phase = tick * 0.1;
        for (int i = 0; i < 20; i++) {
            double angle = (2.0 * Math.PI * i / 20) + phase;
            double ox = Math.cos(angle) * 1.0;
            double oz = Math.sin(angle) * 1.0;
            level.sendParticles(particle, center.x + ox, center.y, center.z + oz, 1, 0, 0, 0, 0);
        }
    }

    private static void spawnLayer2(ServerLevel level, Vec3 center, Entity caster, int tick) {
        var particle = ParticleTypes.ENCHANT;
        double radius = 0.3 + tick * 0.2;
        for (int i = 0; i < 16; i++) {
            double angle = 2.0 * Math.PI * i / 16;
            double ox = Math.cos(angle) * radius;
            double oz = Math.sin(angle) * radius;
            level.sendParticles(particle, center.x + ox, center.y + 0.1, center.z + oz,
                1, 0, 0, 0, 0);
        }
    }

    // ── Math helpers ─────────────────────────────────────────

    private static double[] rotateY(double x, double z, double angle) {
        double cos = Math.cos(angle);
        double sin = Math.sin(angle);
        return new double[]{ x * cos - z * sin, x * sin + z * cos };
    }

    private static Vec3 getLookDirection(Entity entity) {
        if (entity == null) return new Vec3(0, 0, 1);
        return entity.getLookAngle();
    }
}
