package kingdom.smp.effect;

import net.minecraft.core.particles.DustParticleOptions;
import net.minecraft.core.particles.ParticleTypes;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.util.ARGB;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.phys.Vec3;

/**
 * Spell Effect: Rune circle telegraph on ground then vortex eruption
 * Element: dark
 * Layers: 4
 *
 * Generated by Particle Maker — Kingdom SMP
 */
public class VoidRiftEffect {

    /**
     * Spawn the complete spell effect.
     *
     * @param level  The server level
     * @param center Center position of the effect
     * @param caster The casting entity (for direction/look vector), nullable
     * @param tick   Current tick counter (for animation phasing)
     */
    public static void spawn(ServerLevel level, Vec3 center, Entity caster, int tick) {
        if (tick <= 20) spawnLayer0(level, center, caster, tick);
        if (tick <= 20) if (tick % 2 == 0) spawnLayer1(level, center, caster, tick);
        if (tick >= 20) if (tick <= 80) spawnLayer2(level, center, caster, tick);
        if (tick >= 20) if (tick <= 23) spawnLayer3(level, center, caster, tick);
    }

    private static void spawnLayer0(ServerLevel level, Vec3 center, Entity caster, int tick) {
        var particle = new DustParticleOptions(ARGB.colorFromFloat(1f, 0.5f, 0f, 0.7f), 1.0f);
        double rotation = tick * 0.05;
        int ringCount = 40 / 3;
        // Outer ring
        for (int i = 0; i < ringCount; i++) {
            double angle = (2.0 * Math.PI * i / ringCount) + rotation;
            double ox = Math.cos(angle) * 2.5;
            double oz = Math.sin(angle) * 2.5;
            level.sendParticles(particle, center.x + ox, center.y + 0.05, center.z + oz, 1, 0, 0, 0, 0);
        }
        // Inner ring
        double innerR = 2.5 * 0.7;
        for (int i = 0; i < ringCount; i++) {
            double angle = (2.0 * Math.PI * i / ringCount) + rotation;
            double ox = Math.cos(angle) * innerR;
            double oz = Math.sin(angle) * innerR;
            level.sendParticles(particle, center.x + ox, center.y + 0.05, center.z + oz, 1, 0, 0, 0, 0);
        }
        // Star lines
        for (int v = 0; v < 5; v++) {
            double a1 = (2.0 * Math.PI * v / 5) + rotation;
            double a2 = (2.0 * Math.PI * ((v + 2) % 5) / 5) + rotation;
            for (int s = 0; s < 5; s++) {
                double t = (double) s / 4.0;
                double ox = Math.cos(a1) * 2.5 * (1 - t) + Math.cos(a2) * 2.5 * t;
                double oz = Math.sin(a1) * 2.5 * (1 - t) + Math.sin(a2) * 2.5 * t;
                level.sendParticles(particle, center.x + ox, center.y + 0.05, center.z + oz, 1, 0, 0, 0, 0);
            }
        }
    }

    private static void spawnLayer1(ServerLevel level, Vec3 center, Entity caster, int tick) {
        var particle = ParticleTypes.PORTAL;
        double phase = tick * 0.1;
        for (int i = 0; i < 16; i++) {
            double angle = (2.0 * Math.PI * i / 16) + phase;
            double ox = Math.cos(angle) * 2.5;
            double oz = Math.sin(angle) * 2.5;
            level.sendParticles(particle, center.x + ox, center.y, center.z + oz, 1, 0, 0, 0, 0);
        }
    }

    private static void spawnLayer2(ServerLevel level, Vec3 center, Entity caster, int tick) {
        var particle = ParticleTypes.REVERSE_PORTAL;
        double phase = tick * 0.1;
        for (int i = 0; i < 40; i++) {
            double t = (double) i / (40 - 1);
            double r = 1.8 * (0.3 + 0.7 * t);
            double angle = 2.0 * Math.PI * 3.0 * t + phase;
            double ox = Math.cos(angle) * r;
            double oz = Math.sin(angle) * r;
            double oy = t * 4.0;
            level.sendParticles(particle, center.x + ox, center.y + oy, center.z + oz, 1, 0, 0.02, 0, 0.01);
        }
    }

    private static void spawnLayer3(ServerLevel level, Vec3 center, Entity caster, int tick) {
        var particle = new DustParticleOptions(ARGB.colorFromFloat(1f, 0.5f, 0f, 0.7f), 1.2f);
        double golden = Math.PI * (3.0 - Math.sqrt(5.0));
        for (int i = 0; i < 20; i++) {
            double y = 1.0 - (2.0 * i / (20 - 1));
            double r = Math.sqrt(1.0 - y * y);
            double theta = golden * i;
            double nx = r * Math.cos(theta);
            double nz = r * Math.sin(theta);
            double ny = y;
            level.sendParticles(particle, center.x, center.y, center.z,
                0, nx * 0.2, ny * 0.2, nz * 0.2, 1.0);
        }
    }

    // ── Math helpers ─────────────────────────────────────────

    private static double[] rotateY(double x, double z, double angle) {
        double cos = Math.cos(angle);
        double sin = Math.sin(angle);
        return new double[]{ x * cos - z * sin, x * sin + z * cos };
    }

    private static Vec3 getLookDirection(Entity entity) {
        if (entity == null) return new Vec3(0, 0, 1);
        return entity.getLookAngle();
    }
}
