package kingdom.smp.mixin;

import kingdom.smp.access.SlotAccessor;
import kingdom.smp.Ironhold;
import kingdom.smp.client.HopperSlotDebug;
import kingdom.smp.client.ScreenWidgetTuner;
import kingdom.smp.inventory.HopperLayout;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.gui.screens.inventory.AbstractContainerScreen;
import net.minecraft.client.gui.screens.inventory.HopperScreen;
import net.minecraft.client.renderer.RenderPipelines;
import net.minecraft.resources.Identifier;
import net.minecraft.world.entity.player.Inventory;
import net.minecraft.world.inventory.HopperMenu;
import net.minecraft.world.inventory.Slot;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

/**
 * Reskin of the vanilla Hopper screen.
 * Generated by scripts/gen_gui_reskins.py — slot positions are rough; drag-tune in-game with F4.
 */
@Mixin(HopperScreen.class)
public abstract class HopperScreenMixin extends AbstractContainerScreen<HopperMenu> {

    private static final Identifier MAIN_TEXTURE =
            Identifier.fromNamespaceAndPath(Ironhold.MODID, "textures/gui/hopper/hopper_main.png");

    /** Synthesized constructor — never invoked. */
    protected HopperScreenMixin(HopperMenu menu, Inventory inv, net.minecraft.network.chat.Component title) {
        super(menu, inv, title);
    }

    @Inject(method = "<init>", at = @At("RETURN"))
    private void ironhold$resizePanel(HopperMenu menu, Inventory inv,
                                      net.minecraft.network.chat.Component title, CallbackInfo ci) {
        AbstractContainerScreenAccessor acc = (AbstractContainerScreenAccessor) this;
        acc.ironhold$setImageWidth(HopperLayout.MAIN_W);
        acc.ironhold$setImageHeight(HopperLayout.MAIN_H);
        // Labels are NOT force-hidden here — they're tunable via the F4 overlay.
        // To hide a label, drag it off-screen or set its tuned (x, y) to large negatives.
    }

    @Inject(method = "extractBackground", at = @At("HEAD"), cancellable = true)
    private void ironhold$drawCustomBackground(GuiGraphicsExtractor gfx, int mouseX, int mouseY,
                                               float partialTick, CallbackInfo ci) {
        ironhold$applyDebugPositions();
        // Lazy widget capture — only walks children() when the screen instance or widget count changes.
        // Avoids @Inject(method="init") which fails on subclasses that don't redeclare init().
        ScreenWidgetTuner.ensureCaptured(HopperSlotDebug.SCREEN_KEY, this, this.leftPos, this.topPos);
        ScreenWidgetTuner.applyPositions(HopperSlotDebug.SCREEN_KEY, this.leftPos, this.topPos);

        // Capture vanilla label positions on first sight; then apply tuned overrides every frame.
        ScreenWidgetTuner.ensureLabelsCaptured(HopperSlotDebug.SCREEN_KEY, this,
                this.titleLabelX, this.titleLabelY,
                this.inventoryLabelX, this.inventoryLabelY);
        int[] titleXY = ScreenWidgetTuner.labelPos(HopperSlotDebug.SCREEN_KEY, 0);
        int[] invXY   = ScreenWidgetTuner.labelPos(HopperSlotDebug.SCREEN_KEY, 1);
        this.titleLabelX = titleXY[0];
        this.titleLabelY = titleXY[1];
        this.inventoryLabelX = invXY[0];
        this.inventoryLabelY = invXY[1];

        int left = this.leftPos;
        int top = this.topPos;

        gfx.fill(0, 0, this.width, this.height, 0xC0101010);

        // Stretch the hi-res source (HopperLayout.SRC_W×SRC_H) to in-game MAIN_W×MAIN_H.
        gfx.blit(RenderPipelines.GUI_TEXTURED, MAIN_TEXTURE, left, top, 0f, 0f,
                HopperLayout.MAIN_W, HopperLayout.MAIN_H,
                HopperLayout.SRC_W,  HopperLayout.SRC_H,
                HopperLayout.SRC_W,  HopperLayout.SRC_H);

        if (HopperSlotDebug.isEditMode()) {
            ironhold$drawEditModeOverlay(gfx);
        }
        ci.cancel();
    }

    private void ironhold$applyDebugPositions() {
        int n = Math.min(HopperSlotDebug.SLOT_COUNT, this.menu.slots.size());
        for (int i = 0; i < n; i++) {
            int[] xy = HopperSlotDebug.slotPos(i);
            Slot slot = this.menu.slots.get(i);
            SlotAccessor acc = (SlotAccessor) slot;
            acc.ironhold$setX(xy[0]);
            acc.ironhold$setY(xy[1]);
        }
    }

    private void ironhold$drawEditModeOverlay(GuiGraphicsExtractor gfx) {
        gfx.fill(0, 0, this.width, 12, 0xCC000000);
        gfx.text(this.font, "[ironhold edit] " + HopperSlotDebug.summary()
                + "  |  F4=off  Tab=cycle  Arrows=nudge  Drag=move  P=print  R=reset",
                4, 2, 0xFF55FFFF, false);

        int left = this.leftPos;
        int top = this.topPos;
        int sel = HopperSlotDebug.selectedIndex();
        int[] xy = HopperSlotDebug.slotPos(sel);
        int widgetCount = ScreenWidgetTuner.widgetCount(HopperSlotDebug.SCREEN_KEY);
        if (sel < HopperSlotDebug.SLOT_COUNT) {
            // Slot — 16×16 cyan box.
            ironhold$drawOutline(gfx, left + xy[0] - 1, top + xy[1] - 1, 18, 18, 0xFF55FFFF);
        } else if (sel < HopperSlotDebug.SLOT_COUNT + widgetCount) {
            // Widget — orange box from live AbstractWidget bbox.
            int wi = sel - HopperSlotDebug.SLOT_COUNT;
            int[] box = ScreenWidgetTuner.widgetBox(HopperSlotDebug.SCREEN_KEY, wi);
            ironhold$drawOutline(gfx, box[0] - 1, box[1] - 1, box[2] + 2, box[3] + 2, 0xFFFFAA00);
        } else if (sel < HopperSlotDebug.SLOT_COUNT + widgetCount + ScreenWidgetTuner.labelCount(HopperSlotDebug.SCREEN_KEY)) {
            // Label — magenta box (synthetic 60×12 around label origin).
            int li = sel - HopperSlotDebug.SLOT_COUNT - widgetCount;
            int[] box = ScreenWidgetTuner.labelBox(HopperSlotDebug.SCREEN_KEY, li, left, top);
            ironhold$drawOutline(gfx, box[0], box[1], box[2], box[3], 0xFFFF55FF);
        } else {
            // Anchor — yellow box (synthetic 24×24 around anchor origin).
            int ai = sel - HopperSlotDebug.SLOT_COUNT - widgetCount - ScreenWidgetTuner.labelCount(HopperSlotDebug.SCREEN_KEY);
            int[] box = ScreenWidgetTuner.anchorBox(HopperSlotDebug.SCREEN_KEY, ai, left, top);
            ironhold$drawOutline(gfx, box[0], box[1], box[2], box[3], 0xFFFFFF00);
        }
    }

    private static void ironhold$drawOutline(GuiGraphicsExtractor gfx, int x, int y, int w, int h, int color) {
        gfx.fill(x,         y,         x + w, y + 1, color);
        gfx.fill(x,         y + h - 1, x + w, y + h, color);
        gfx.fill(x,         y,         x + 1, y + h, color);
        gfx.fill(x + w - 1, y,         x + w, y + h, color);
    }
}
