package kingdom.smp.entity;

import net.minecraft.util.Mth;
import net.minecraft.util.RandomSource;
import net.minecraft.world.level.storage.ValueInput;
import net.minecraft.world.level.storage.ValueOutput;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * Full personality state for a Kingdom Villager. Mutable — mood and opinions shift over time.
 * Persisted via ValueOutput/ValueInput on the entity.
 */
public final class VillagerPersonality {

    // ── Identity ─────────────────────────────────────────────────────────────
    private String name;
    private VillagerTemperament temperament;

    // ── Permanent traits (set at spawn, never change) ────────────────────────
    private float friendliness; // 0–1: warmth, gift quality, helpfulness
    private float boldness;     // 0–1: reaction to danger, willingness to engage
    private float energy;       // 0–1: movement speed multiplier, emote frequency

    // ── Dynamic state ────────────────────────────────────────────────────────
    private float mood;         // -1 to +1: shifts based on events, decays toward 0

    // ── Talker-only state ────────────────────────────────────────────────────
    private String backstory;                       // generated by LLM on first interaction
    private final List<String> conversationMemory;  // last 8 exchange summaries
    private final Map<UUID, Integer> playerOpinions; // -100 to +100 per player

    public VillagerPersonality() {
        this.name = "Villager";
        this.temperament = VillagerTemperament.STOIC;
        this.friendliness = 0.5f;
        this.boldness = 0.5f;
        this.energy = 0.5f;
        this.mood = 0.0f;
        this.backstory = "";
        this.conversationMemory = new ArrayList<>();
        this.playerOpinions = new HashMap<>();
    }

    /** Randomize personality on first spawn. */
    public void randomize(RandomSource rand, VillagerProfession profession) {
        this.temperament = VillagerTemperament.random(rand);
        this.name = profession.randomName(rand);

        // Base from temperament + random jitter (+-0.15)
        this.friendliness = jitter(rand, temperament.baseFriendliness());
        this.boldness     = jitter(rand, temperament.baseBoldness());
        this.energy       = jitter(rand, temperament.baseEnergy());
        this.mood         = (rand.nextFloat() - 0.5f) * 0.4f; // slight starting bias
    }

    private static float jitter(RandomSource rand, float base) {
        return Mth.clamp(base + (rand.nextFloat() - 0.5f) * 0.3f, 0.0f, 1.0f);
    }

    // ── Mood system ──────────────────────────────────────────────────────────

    /** Shift mood by delta, clamped to [-1, 1]. */
    public void shiftMood(float delta) {
        this.mood = Mth.clamp(this.mood + delta, -1.0f, 1.0f);
    }

    /** Decay mood toward neutral. Call every ~100 ticks. */
    public void decayMood() {
        if (Math.abs(mood) < 0.01f) {
            mood = 0.0f;
        } else {
            mood *= 0.95f;
        }
    }

    /** Current effective friendliness = base + mood influence. */
    public float effectiveFriendliness() {
        return Mth.clamp(friendliness + mood * 0.2f, 0.0f, 1.0f);
    }

    // ── Player opinions (talkers only) ───────────────────────────────────────

    public int getOpinion(UUID playerId) {
        return playerOpinions.getOrDefault(playerId, 0);
    }

    public void shiftOpinion(UUID playerId, int delta) {
        int current = getOpinion(playerId);
        playerOpinions.put(playerId, Mth.clamp(current + delta, -100, 100));
    }

    // ── Conversation memory (talkers only) ───────────────────────────────────

    public void addMemory(String summary) {
        conversationMemory.add(summary);
        while (conversationMemory.size() > 8) {
            conversationMemory.removeFirst();
        }
    }

    // ── LLM prompt builder (talkers only) ────────────────────────────────────

    public String buildSystemPrompt(VillagerProfession profession) {
        StringBuilder sb = new StringBuilder();
        sb.append("You are ").append(name).append(", a ").append(profession.displayName())
          .append(" in the medieval Kingdom SMP Minecraft server.\n\n");

        sb.append("Your temperament: ").append(temperament.llmDescription()).append("\n");
        sb.append("Personality traits — friendliness: ").append(fmtPct(friendliness))
          .append(", boldness: ").append(fmtPct(boldness))
          .append(", energy: ").append(fmtPct(energy)).append("\n");
        sb.append("Current mood: ").append(moodDescription()).append("\n\n");

        sb.append("Your role: ").append(profession.llmFlavor()).append("\n\n");

        if (!backstory.isEmpty()) {
            sb.append("Your backstory: ").append(backstory).append("\n\n");
        }

        if (!conversationMemory.isEmpty()) {
            sb.append("Your memories of past conversations:\n");
            for (String mem : conversationMemory) {
                sb.append("- ").append(mem).append("\n");
            }
            sb.append("\n");
        }

        sb.append("""
            RULES:
            - Stay in character at all times. Never break the fourth wall.
            - Your dialogue should reflect your temperament and current mood.
            - Keep responses to 1-3 sentences, under 200 characters for dialogue.
            - If this is your first time meeting this player, introduce yourself briefly.
            - If you have memories of this player, reference them naturally.

            You MUST respond ONLY with valid JSON:
            {"dialogue": "<your spoken words>", "memory": "<one-line summary of this exchange, under 100 chars>", "mood_shift": <float -0.3 to 0.3>, "opinion_shift": <int -10 to 10>}
            """);

        return sb.toString();
    }

    public String buildUserMessage(String playerName, String playerClass, int playerLevel,
                                   UUID playerId) {
        int opinion = getOpinion(playerId);
        String opinionDesc;
        if (opinion > 50) opinionDesc = "You consider them a close friend.";
        else if (opinion > 20) opinionDesc = "You are fond of them.";
        else if (opinion > -20) opinionDesc = "You are neutral toward them.";
        else if (opinion > -50) opinionDesc = "You are wary of them.";
        else opinionDesc = "You distrust them deeply.";

        return String.format(
            "Player \"%s\" (class: %s, level: %d) approaches you. %s Current time: %s.",
            playerName, playerClass, playerLevel, opinionDesc,
            mood > 0.3f ? "you're in good spirits" :
            mood < -0.3f ? "you're in a foul mood" : "you're feeling neutral");
    }

    private String moodDescription() {
        if (mood > 0.6f) return "very happy";
        if (mood > 0.2f) return "content";
        if (mood > -0.2f) return "neutral";
        if (mood > -0.6f) return "irritable";
        return "miserable";
    }

    private static String fmtPct(float val) {
        return String.format("%.0f%%", val * 100);
    }

    // ── Flat save/load via ValueOutput/ValueInput ────────────────────────────
    // All personality fields are flattened with a "P_" prefix to avoid collisions.

    public void save(ValueOutput out) {
        out.putString("P_Name", name);
        out.putString("P_Temperament", temperament.id());
        out.putFloat("P_Friendliness", friendliness);
        out.putFloat("P_Boldness", boldness);
        out.putFloat("P_Energy", energy);
        out.putFloat("P_Mood", mood);
        out.putString("P_Backstory", backstory);

        // Conversation memory as numbered entries
        out.putInt("P_MemCount", conversationMemory.size());
        for (int i = 0; i < conversationMemory.size(); i++) {
            out.putString("P_Mem" + i, conversationMemory.get(i));
        }

        // Player opinions as numbered entries
        List<Map.Entry<UUID, Integer>> opList = new ArrayList<>(playerOpinions.entrySet());
        out.putInt("P_OpCount", opList.size());
        for (int i = 0; i < opList.size(); i++) {
            out.putString("P_OpUUID" + i, opList.get(i).getKey().toString());
            out.putInt("P_OpVal" + i, opList.get(i).getValue());
        }
    }

    public void load(ValueInput in) {
        this.name = in.getStringOr("P_Name", "Villager");
        this.temperament = VillagerTemperament.fromId(in.getStringOr("P_Temperament", "stoic"));
        this.friendliness = in.getFloatOr("P_Friendliness", 0.5f);
        this.boldness = in.getFloatOr("P_Boldness", 0.5f);
        this.energy = in.getFloatOr("P_Energy", 0.5f);
        this.mood = in.getFloatOr("P_Mood", 0.0f);
        this.backstory = in.getStringOr("P_Backstory", "");

        conversationMemory.clear();
        int memCount = in.getIntOr("P_MemCount", 0);
        for (int i = 0; i < memCount; i++) {
            String mem = in.getStringOr("P_Mem" + i, "");
            if (!mem.isEmpty()) conversationMemory.add(mem);
        }

        playerOpinions.clear();
        int opCount = in.getIntOr("P_OpCount", 0);
        for (int i = 0; i < opCount; i++) {
            String uuidStr = in.getStringOr("P_OpUUID" + i, "");
            if (!uuidStr.isEmpty()) {
                try {
                    playerOpinions.put(UUID.fromString(uuidStr), in.getIntOr("P_OpVal" + i, 0));
                } catch (IllegalArgumentException ignored) {}
            }
        }
    }

    // ── Getters ──────────────────────────────────────────────────────────────

    public String name() { return name; }
    public VillagerTemperament temperament() { return temperament; }
    public float friendliness() { return friendliness; }
    public float boldness() { return boldness; }
    public float energy() { return energy; }
    public float mood() { return mood; }
    public String backstory() { return backstory; }
    public List<String> conversationMemory() { return conversationMemory; }
    public Map<UUID, Integer> playerOpinions() { return playerOpinions; }

    public void setBackstory(String backstory) { this.backstory = backstory; }
    public void setName(String name) { this.name = name; }
}
