package kingdom.smp.entity.goal;

import kingdom.smp.entity.ArcaneMageEntity;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.ai.goal.Goal;
import net.minecraft.world.phys.Vec3;

import java.util.EnumSet;

/**
 * Makes the Arcane Mage back away from targets to maintain casting range.
 * Similar to skeleton retreat AI but with preference for 8-12 block distance.
 *
 * Generated by Particle Maker — Kingdom SMP
 */
public class MageRetreatGoal extends Goal {

    private final ArcaneMageEntity mage;
    private final double preferredDistance;
    private final double speed;

    public MageRetreatGoal(ArcaneMageEntity mage, double preferredDistance, double speed) {
        this.mage = mage;
        this.preferredDistance = preferredDistance;
        this.speed = speed;
        this.setFlags(EnumSet.of(Flag.MOVE));
    }

    @Override
    public boolean canUse() {
        LivingEntity target = mage.getTarget();
        if (target == null) return false;
        if (mage.isCasting()) return false; // don't move while casting
        return mage.distanceTo(target) < preferredDistance * 0.6; // too close
    }

    @Override
    public boolean canContinueToUse() {
        LivingEntity target = mage.getTarget();
        if (target == null) return false;
        if (mage.isCasting()) return false;
        return mage.distanceTo(target) < preferredDistance * 0.8;
    }

    @Override
    public void tick() {
        LivingEntity target = mage.getTarget();
        if (target == null) return;

        // Move directly away from target
        Vec3 diff = mage.position().subtract(target.position()).normalize();
        double retreatX = mage.getX() + diff.x * 4;
        double retreatZ = mage.getZ() + diff.z * 4;

        mage.getNavigation().moveTo(retreatX, mage.getY(), retreatZ, speed);
        mage.getLookControl().setLookAt(target, 30.0F, 30.0F);
    }
}
