package kingdom.smp.entity.goal;

import kingdom.smp.entity.ArcaneMageEntity;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.ai.goal.Goal;

import java.util.EnumSet;

/**
 * Custom AI goal that selects and executes spells based on range, cooldowns, and HP.
 *
 * Spell selection priority:
 *   1. Soul Shield  — if HP < 40% and shield off cooldown (defensive)
 *   2. Void Rift    — if target within 6 blocks and off cooldown (area denial)
 *   3. Arcane Barrage — if target within 16 blocks (primary ranged)
 *   4. Teleport away — if target within 3 blocks (escape melee range)
 *
 * Generated by Particle Maker — Kingdom SMP
 */
public class SpellCastGoal extends Goal {

    private final ArcaneMageEntity mage;
    private final double maxRange;
    private int castTicksRemaining;
    private ArcaneMageEntity.SpellType currentSpell;

    public SpellCastGoal(ArcaneMageEntity mage, double maxRange) {
        this.mage = mage;
        this.maxRange = maxRange;
        this.setFlags(EnumSet.of(Flag.MOVE, Flag.LOOK));
    }

    @Override
    public boolean canUse() {
        LivingEntity target = mage.getTarget();
        if (target == null || !target.isAlive()) return false;
        if (mage.isCasting()) return false; // already mid-cast
        return mage.distanceTo(target) <= maxRange && mage.hasLineOfSight(target);
    }

    @Override
    public boolean canContinueToUse() {
        LivingEntity target = mage.getTarget();
        return target != null && target.isAlive() && castTicksRemaining > 0;
    }

    @Override
    public void start() {
        LivingEntity target = mage.getTarget();
        if (target == null) return;

        double dist = mage.distanceTo(target);
        float hpPercent = mage.getHealth() / mage.getMaxHealth();

        // Pick spell based on situation
        currentSpell = selectSpell(dist, hpPercent);
        if (currentSpell == null) return;

        castTicksRemaining = currentSpell.castTicks;
        mage.startCasting(currentSpell);
        mage.getLookControl().setLookAt(target, 30.0F, 30.0F);
        mage.getNavigation().stop(); // stand still while casting
    }

    @Override
    public void tick() {
        LivingEntity target = mage.getTarget();
        if (target != null) {
            mage.getLookControl().setLookAt(target, 30.0F, 30.0F);
        }

        castTicksRemaining--;
        if (castTicksRemaining <= 0 && currentSpell != null) {
            mage.executeSpell(currentSpell, target);
            mage.finishCasting();
        }
    }

    @Override
    public void stop() {
        castTicksRemaining = 0;
        currentSpell = null;
        if (mage.isCasting()) {
            mage.finishCasting();
        }
    }

    private ArcaneMageEntity.SpellType selectSpell(double distance, float hpPercent) {
        // 1. Soul Shield at low HP
        if (hpPercent < 0.4f && mage.canUseSpell(ArcaneMageEntity.SpellType.SOUL_SHIELD)) {
            return ArcaneMageEntity.SpellType.SOUL_SHIELD;
        }

        // 2. Teleport if too close
        if (distance < 3.0 && mage.canUseSpell(ArcaneMageEntity.SpellType.TELEPORT)) {
            return ArcaneMageEntity.SpellType.TELEPORT;
        }

        // 3. Void Rift for mid-range area denial
        if (distance < 8.0 && mage.canUseSpell(ArcaneMageEntity.SpellType.VOID_RIFT)) {
            return ArcaneMageEntity.SpellType.VOID_RIFT;
        }

        // 4. Arcane Barrage — primary ranged
        if (distance <= maxRange && mage.canUseSpell(ArcaneMageEntity.SpellType.ARCANE_BARRAGE)) {
            return ArcaneMageEntity.SpellType.ARCANE_BARRAGE;
        }

        return null;
    }
}
