package kingdom.smp.client;

import net.minecraft.ChatFormatting;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.screens.inventory.AbstractContainerScreen;
import net.minecraft.client.gui.screens.inventory.AnvilScreen;
import net.minecraft.network.chat.Component;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.neoforge.client.event.ScreenEvent;
import org.lwjgl.glfw.GLFW;

/**
 * F4 / Tab / arrow / drag debug overlay for the Ironhold Anvil reskin.
 * Generated by scripts/gen_gui_reskins.py.
 */
public final class AnvilSlotDebugHandler {
    private AnvilSlotDebugHandler() {}

    private static boolean isAnvil(Object screen) {
        return screen instanceof AnvilScreen;
    }

    @SubscribeEvent
    public static void onKey(ScreenEvent.KeyPressed.Pre event) {
        if (!isAnvil(event.getScreen())) return;
        int key = event.getKeyEvent().key();
        boolean shift = (event.getKeyEvent().modifiers() & GLFW.GLFW_MOD_SHIFT) != 0;

        if (key == GLFW.GLFW_KEY_F4) {
            AnvilSlotDebug.toggleEditMode();
            chat("§b[ironhold/anvil] edit mode " + (AnvilSlotDebug.isEditMode() ? "ON" : "OFF"));
            event.setCanceled(true);
            return;
        }
        if (!AnvilSlotDebug.isEditMode()) return;
        int step = shift ? 5 : 1;
        switch (key) {
            case GLFW.GLFW_KEY_TAB -> { AnvilSlotDebug.cycleSelection(shift ? -1 : 1); chat(AnvilSlotDebug.summary()); }
            case GLFW.GLFW_KEY_LEFT  -> { AnvilSlotDebug.nudge(-step, 0); chat(AnvilSlotDebug.summary()); }
            case GLFW.GLFW_KEY_RIGHT -> { AnvilSlotDebug.nudge( step, 0); chat(AnvilSlotDebug.summary()); }
            case GLFW.GLFW_KEY_UP    -> { AnvilSlotDebug.nudge(0, -step); chat(AnvilSlotDebug.summary()); }
            case GLFW.GLFW_KEY_DOWN  -> { AnvilSlotDebug.nudge(0,  step); chat(AnvilSlotDebug.summary()); }
            case GLFW.GLFW_KEY_P -> {
                String dump = AnvilSlotDebug.printJava();
                System.out.println(dump);
                for (String line : dump.split("\n")) chat(line);
            }
            case GLFW.GLFW_KEY_R -> { AnvilSlotDebug.resetAll(); chat("§e[ironhold/anvil] reset to defaults"); }
            default -> { return; }
        }
        event.setCanceled(true);
    }

    @SubscribeEvent
    public static void onMouseDown(ScreenEvent.MouseButtonPressed.Pre event) {
        if (!isAnvil(event.getScreen())) return;
        if (!AnvilSlotDebug.isEditMode()) return;
        if (event.getMouseButtonEvent().button() != 0) return;
        AbstractContainerScreen<?> s = (AbstractContainerScreen<?>) event.getScreen();
        int mx = (int) event.getMouseX();
        int my = (int) event.getMouseY();
        if (AnvilSlotDebug.tryStartDrag(mx, my, s.getGuiLeft(), s.getGuiTop())) {
            event.setCanceled(true);
        }
    }

    @SubscribeEvent
    public static void onMouseDrag(ScreenEvent.MouseDragged.Pre event) {
        if (!isAnvil(event.getScreen())) return;
        if (!AnvilSlotDebug.isDragging()) return;
        AbstractContainerScreen<?> s = (AbstractContainerScreen<?>) event.getScreen();
        int mx = (int) event.getMouseX();
        int my = (int) event.getMouseY();
        AnvilSlotDebug.updateDrag(mx, my, s.getGuiLeft(), s.getGuiTop());
        event.setCanceled(true);
    }

    @SubscribeEvent
    public static void onMouseUp(ScreenEvent.MouseButtonReleased.Pre event) {
        if (!isAnvil(event.getScreen())) return;
        if (!AnvilSlotDebug.isDragging()) return;
        AnvilSlotDebug.endDrag();
        chat(AnvilSlotDebug.summary());
        event.setCanceled(true);
    }

    private static void chat(String msg) {
        Minecraft mc = Minecraft.getInstance();
        if (mc.player != null) mc.player.sendSystemMessage(Component.literal(msg).withStyle(ChatFormatting.AQUA));
    }
}
