package kingdom.smp.client;

import kingdom.smp.inventory.BrewingStandLayout;

/**
 * Live-tunable layout for the Ironhold BrewingStand screen reskin.
 * Generated by scripts/gen_gui_reskins.py.
 *
 * <p>Selection index spans a unified range [0 .. SLOT_COUNT + widgetCount):
 * <ul>
 *   <li>0..CONTAINER_COUNT-1 → container-side slots</li>
 *   <li>CONTAINER_COUNT..SLOT_COUNT-1 → player inventory + hotbar</li>
 *   <li>SLOT_COUNT.. → captured AbstractWidgets routed through {@link ScreenWidgetTuner}</li>
 * </ul>
 */
public final class BrewingStandSlotDebug {
    private BrewingStandSlotDebug() {}

    public static final String SCREEN_KEY = "brewing_stand";
    public static final int CONTAINER_COUNT = 5;
    public static final int SLOT_COUNT = 41;

    private static final String[] CONTAINER_LABELS = new String[] {
        "bottle0",
        "bottle1",
        "bottle2",
        "ingredient",
        "fuel",
    };

    private static int[][] positions = makeDefaults();
    private static int selected = 0;
    private static boolean editMode = false;
    /** -1 = no drag; 0..SLOT_COUNT-1 = slot index; ≥SLOT_COUNT = widget index + SLOT_COUNT. */
    private static int dragIndex = -1;
    private static int dragOffsetX, dragOffsetY;

    private static int[][] makeDefaults() {
        int[][] p = new int[SLOT_COUNT][2];
        for (int i = 0; i < CONTAINER_COUNT; i++) {
            p[i] = new int[]{ BrewingStandLayout.CONTAINER_SLOTS[i][0], BrewingStandLayout.CONTAINER_SLOTS[i][1] };
        }
        for (int row = 0; row < 3; row++) {
            for (int col = 0; col < 9; col++) {
                p[CONTAINER_COUNT + row * 9 + col] = new int[]{
                    BrewingStandLayout.INV_X + col * BrewingStandLayout.INV_COL_STEP,
                    BrewingStandLayout.INV_Y + row * BrewingStandLayout.INV_ROW_STEP
                };
            }
        }
        for (int col = 0; col < 9; col++) {
            p[CONTAINER_COUNT + 27 + col] = new int[]{
                BrewingStandLayout.INV_X + col * BrewingStandLayout.INV_COL_STEP,
                BrewingStandLayout.HOTBAR_Y
            };
        }
        return p;
    }

    private static int totalCount() {
        return SLOT_COUNT
             + ScreenWidgetTuner.widgetCount(SCREEN_KEY)
             + ScreenWidgetTuner.labelCount(BrewingStandSlotDebug.SCREEN_KEY)
             + ScreenWidgetTuner.anchorCount(SCREEN_KEY);
    }

    /** Returns 0=slot, 1=widget, 2=label, 3=anchor for the unified index. */
    private static int rangeOf(int idx) {
        int wc = ScreenWidgetTuner.widgetCount(SCREEN_KEY);
        if (idx < SLOT_COUNT) return 0;
        if (idx < SLOT_COUNT + wc) return 1;
        if (idx < SLOT_COUNT + wc + ScreenWidgetTuner.labelCount(BrewingStandSlotDebug.SCREEN_KEY)) return 2;
        return 3;
    }

    private static int widgetIdx(int idx) { return idx - SLOT_COUNT; }
    private static int labelIdx(int idx)  { return idx - SLOT_COUNT - ScreenWidgetTuner.widgetCount(SCREEN_KEY); }
    private static int anchorIdx(int idx) { return idx - SLOT_COUNT - ScreenWidgetTuner.widgetCount(SCREEN_KEY) - ScreenWidgetTuner.labelCount(BrewingStandSlotDebug.SCREEN_KEY); }

    public static boolean isEditMode() { return editMode; }
    public static void toggleEditMode() { editMode = !editMode; }
    public static int selectedIndex() { return selected; }

    public static void cycleSelection(int delta) {
        int total = totalCount();
        if (total <= 0) return;
        selected = ((selected + delta) % total + total) % total;
    }

    public static int[] slotPos(int idx) {
        if (idx < 0) return new int[]{0, 0};
        switch (rangeOf(idx)) {
            case 0:  return positions[idx];
            case 1:  return ScreenWidgetTuner.widgetPos(SCREEN_KEY, widgetIdx(idx));
            case 2:  return ScreenWidgetTuner.labelPos(SCREEN_KEY, labelIdx(idx));
            default: return ScreenWidgetTuner.anchorPos(SCREEN_KEY, anchorIdx(idx));
        }
    }

    public static void nudge(int dx, int dy) {
        switch (rangeOf(selected)) {
            case 0 -> { positions[selected][0] += dx; positions[selected][1] += dy; }
            case 1 -> ScreenWidgetTuner.nudgeWidget(SCREEN_KEY, widgetIdx(selected), dx, dy);
            case 2 -> ScreenWidgetTuner.nudgeLabel(SCREEN_KEY, labelIdx(selected), dx, dy);
            default -> ScreenWidgetTuner.nudgeAnchor(SCREEN_KEY, anchorIdx(selected), dx, dy);
        }
    }

    public static boolean tryStartDrag(int mx, int my, int leftPos, int topPos) {
        // 1. Slot hit-boxes (16×16, panel-relative).
        for (int i = 0; i < SLOT_COUNT; i++) {
            int sx = leftPos + positions[i][0];
            int sy = topPos + positions[i][1];
            if (mx >= sx && mx < sx + 16 && my >= sy && my < sy + 16) {
                dragIndex = i;
                dragOffsetX = mx - sx;
                dragOffsetY = my - sy;
                selected = i;
                return true;
            }
        }
        // 2. Widget hit-boxes (absolute).
        int wi = ScreenWidgetTuner.tryStartDragWidget(SCREEN_KEY, mx, my);
        if (wi >= 0) {
            int[] abs = ScreenWidgetTuner.widgetAbsPos(SCREEN_KEY, wi);
            dragIndex = SLOT_COUNT + wi;
            dragOffsetX = mx - abs[0];
            dragOffsetY = my - abs[1];
            selected = SLOT_COUNT + wi;
            return true;
        }
        // 3. Label hit-boxes (synthetic 60×10 around label origin).
        int li = ScreenWidgetTuner.tryStartDragLabel(SCREEN_KEY, mx, my, leftPos, topPos);
        if (li >= 0) {
            int[] rel = ScreenWidgetTuner.labelPos(SCREEN_KEY, li);
            int absX = leftPos + rel[0];
            int absY = topPos + rel[1];
            int widgetCount = ScreenWidgetTuner.widgetCount(SCREEN_KEY);
            dragIndex = SLOT_COUNT + widgetCount + li;
            dragOffsetX = mx - absX;
            dragOffsetY = my - absY;
            selected = dragIndex;
            return true;
        }
        // 4. Anchor hit-boxes (synthetic 24×24 around anchor origin).
        int ai = ScreenWidgetTuner.tryStartDragAnchor(SCREEN_KEY, mx, my, leftPos, topPos);
        if (ai >= 0) {
            int[] rel = ScreenWidgetTuner.anchorPos(SCREEN_KEY, ai);
            int absX = leftPos + rel[0];
            int absY = topPos + rel[1];
            int widgetCount = ScreenWidgetTuner.widgetCount(SCREEN_KEY);
            dragIndex = SLOT_COUNT + widgetCount + ScreenWidgetTuner.labelCount(BrewingStandSlotDebug.SCREEN_KEY) + ai;
            dragOffsetX = mx - absX;
            dragOffsetY = my - absY;
            selected = dragIndex;
            return true;
        }
        return false;
    }

    public static boolean isDragging() { return dragIndex >= 0; }

    public static void updateDrag(int mx, int my, int leftPos, int topPos) {
        if (dragIndex < 0) return;
        int relX = mx - leftPos - dragOffsetX;
        int relY = my - topPos - dragOffsetY;
        switch (rangeOf(dragIndex)) {
            case 0 -> { positions[dragIndex][0] = relX; positions[dragIndex][1] = relY; }
            case 1 -> ScreenWidgetTuner.setWidgetRelPos(SCREEN_KEY, widgetIdx(dragIndex), relX, relY);
            case 2 -> ScreenWidgetTuner.setLabelRelPos(SCREEN_KEY, labelIdx(dragIndex), relX, relY);
            default -> ScreenWidgetTuner.setAnchorRelPos(SCREEN_KEY, anchorIdx(dragIndex), relX, relY);
        }
    }

    public static void endDrag() { dragIndex = -1; }
    public static void resetAll() { positions = makeDefaults(); ScreenWidgetTuner.resetScreen(SCREEN_KEY); }

    private static String slotName(int i) {
        if (i < CONTAINER_COUNT) return CONTAINER_LABELS[i];
        if (i < CONTAINER_COUNT + 27) return "inv[" + (i - CONTAINER_COUNT) + "]";
        if (i < SLOT_COUNT) return "hotbar[" + (i - CONTAINER_COUNT - 27) + "]";
        int wc = ScreenWidgetTuner.widgetCount(SCREEN_KEY);
        if (i < SLOT_COUNT + wc) return ScreenWidgetTuner.widgetLabel(SCREEN_KEY, widgetIdx(i));
        if (i < SLOT_COUNT + wc + ScreenWidgetTuner.labelCount(BrewingStandSlotDebug.SCREEN_KEY)) return ScreenWidgetTuner.labelName(labelIdx(i));
        return ScreenWidgetTuner.anchorName(SCREEN_KEY, anchorIdx(i));
    }

    public static String summary() {
        int[] p = slotPos(selected);
        return String.format("[edit] BREWINGSTAND %d (%s) -> (%d, %d)  [total=%d]",
                selected, slotName(selected), p[0], p[1], totalCount());
    }

    public static String printJava() {
        StringBuilder sb = new StringBuilder("=== Ironhold brewing_stand layout ===\n");
        for (int i = 0; i < SLOT_COUNT; i++) {
            sb.append(String.format("/* %2d %-14s */ { %3d, %3d },%n",
                    i, slotName(i), positions[i][0], positions[i][1]));
        }
        sb.append(ScreenWidgetTuner.printJava(SCREEN_KEY));
        return sb.toString();
    }
}
