package kingdom.smp.client;

import net.minecraft.ChatFormatting;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.screens.inventory.AbstractContainerScreen;
import net.minecraft.client.gui.screens.inventory.StonecutterScreen;
import net.minecraft.network.chat.Component;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.neoforge.client.event.ScreenEvent;
import org.lwjgl.glfw.GLFW;

/**
 * F4 / Tab / arrow / drag debug overlay for the Ironhold Stonecutter reskin.
 * Generated by scripts/gen_gui_reskins.py.
 */
public final class StonecutterSlotDebugHandler {
    private StonecutterSlotDebugHandler() {}

    private static boolean isStonecutter(Object screen) {
        return screen instanceof StonecutterScreen;
    }

    @SubscribeEvent
    public static void onKey(ScreenEvent.KeyPressed.Pre event) {
        if (!isStonecutter(event.getScreen())) return;
        int key = event.getKeyEvent().key();
        boolean shift = (event.getKeyEvent().modifiers() & GLFW.GLFW_MOD_SHIFT) != 0;

        if (key == GLFW.GLFW_KEY_F4) {
            StonecutterSlotDebug.toggleEditMode();
            chat("§b[ironhold/stonecutter] edit mode " + (StonecutterSlotDebug.isEditMode() ? "ON" : "OFF"));
            event.setCanceled(true);
            return;
        }
        if (!StonecutterSlotDebug.isEditMode()) return;
        int step = shift ? 5 : 1;
        switch (key) {
            case GLFW.GLFW_KEY_TAB -> { StonecutterSlotDebug.cycleSelection(shift ? -1 : 1); chat(StonecutterSlotDebug.summary()); }
            case GLFW.GLFW_KEY_LEFT  -> { StonecutterSlotDebug.nudge(-step, 0); chat(StonecutterSlotDebug.summary()); }
            case GLFW.GLFW_KEY_RIGHT -> { StonecutterSlotDebug.nudge( step, 0); chat(StonecutterSlotDebug.summary()); }
            case GLFW.GLFW_KEY_UP    -> { StonecutterSlotDebug.nudge(0, -step); chat(StonecutterSlotDebug.summary()); }
            case GLFW.GLFW_KEY_DOWN  -> { StonecutterSlotDebug.nudge(0,  step); chat(StonecutterSlotDebug.summary()); }
            case GLFW.GLFW_KEY_P -> {
                String dump = StonecutterSlotDebug.printJava();
                System.out.println(dump);
                for (String line : dump.split("\n")) chat(line);
            }
            case GLFW.GLFW_KEY_R -> { StonecutterSlotDebug.resetAll(); chat("§e[ironhold/stonecutter] reset to defaults"); }
            default -> { return; }
        }
        event.setCanceled(true);
    }

    @SubscribeEvent
    public static void onMouseDown(ScreenEvent.MouseButtonPressed.Pre event) {
        if (!isStonecutter(event.getScreen())) return;
        if (!StonecutterSlotDebug.isEditMode()) return;
        if (event.getMouseButtonEvent().button() != 0) return;
        AbstractContainerScreen<?> s = (AbstractContainerScreen<?>) event.getScreen();
        int mx = (int) event.getMouseX();
        int my = (int) event.getMouseY();
        if (StonecutterSlotDebug.tryStartDrag(mx, my, s.getGuiLeft(), s.getGuiTop())) {
            event.setCanceled(true);
        }
    }

    @SubscribeEvent
    public static void onMouseDrag(ScreenEvent.MouseDragged.Pre event) {
        if (!isStonecutter(event.getScreen())) return;
        if (!StonecutterSlotDebug.isDragging()) return;
        AbstractContainerScreen<?> s = (AbstractContainerScreen<?>) event.getScreen();
        int mx = (int) event.getMouseX();
        int my = (int) event.getMouseY();
        StonecutterSlotDebug.updateDrag(mx, my, s.getGuiLeft(), s.getGuiTop());
        event.setCanceled(true);
    }

    @SubscribeEvent
    public static void onMouseUp(ScreenEvent.MouseButtonReleased.Pre event) {
        if (!isStonecutter(event.getScreen())) return;
        if (!StonecutterSlotDebug.isDragging()) return;
        StonecutterSlotDebug.endDrag();
        chat(StonecutterSlotDebug.summary());
        event.setCanceled(true);
    }

    private static void chat(String msg) {
        Minecraft mc = Minecraft.getInstance();
        if (mc.player != null) mc.player.sendSystemMessage(Component.literal(msg).withStyle(ChatFormatting.AQUA));
    }
}
