package kingdom.smp.inventory;

import kingdom.smp.client.ScreenWidgetTuner;

/**
 * Layout for the Ironhold Anvil screen reskin. Generated by scripts/gen_gui_reskins.py.
 *
 * <p>Source texture anvil_main.png (700×698) is blit-scaled to 280×280 in-game.
 *
 * <p>Widget + label defaults below are baked in from F4-tuned in-game sessions. To update them,
 * tune in-game, hit P, copy values into scripts/gen_gui_reskins.py SPECS for "anvil", regenerate.
 */
public final class AnvilLayout {
    private AnvilLayout() {}

    public static final int MAIN_W = 280;
    public static final int MAIN_H = 280;
    public static final int SRC_W  = 700;
    public static final int SRC_H  = 698;

    /** Container-side slot positions (in slot-index order). */
    public static final int[][] CONTAINER_SLOTS = new int[][] {
        {  60,  70 },  // in_left
        { 110,  70 },  // in_right
        { 195,  70 },  // out
    };

    /** 3×9 main inventory top-left. */
    public static final int INV_X = 24;
    public static final int INV_Y = 158;
    public static final int HOTBAR_Y = 230;
    public static final int INV_COL_STEP = 26;
    public static final int INV_ROW_STEP = 22;

    /** Static-init block registers widget + label defaults and anchor origins so they apply on first screen open. */
    static {
        // (no widget defaults baked in yet — tune in-game with F4 then bake)
    }
}
