package kingdom.smp.inventory;

import kingdom.smp.client.ScreenWidgetTuner;

/**
 * Layout for the Ironhold Beacon screen reskin. Generated by scripts/gen_gui_reskins.py.
 *
 * <p>Source texture beacon_main.png (833×826) is blit-scaled to 290×287 in-game.
 *
 * <p>Widget + label defaults below are baked in from F4-tuned in-game sessions. To update them,
 * tune in-game, hit P, copy values into scripts/gen_gui_reskins.py SPECS for "beacon", regenerate.
 */
public final class BeaconLayout {
    private BeaconLayout() {}

    public static final int MAIN_W = 290;
    public static final int MAIN_H = 287;
    public static final int SRC_W  = 833;
    public static final int SRC_H  = 826;

    /** Container-side slot positions (in slot-index order). */
    public static final int[][] CONTAINER_SLOTS = new int[][] {
        { 169, 132 },  // payment
    };

    /** 3×9 main inventory top-left. */
    public static final int INV_X = 42;
    public static final int INV_Y = 165;
    public static final int HOTBAR_Y = 245;
    public static final int INV_COL_STEP = 24;
    public static final int INV_ROW_STEP = 24;

    /** Static-init block registers widget + label defaults and anchor origins so they apply on first screen open. */
    static {
        ScreenWidgetTuner.disableLabels("beacon");
        ScreenWidgetTuner.setDefaultWidgetPos("beacon", "BeaconPowerButton:0",  64,  31);
        ScreenWidgetTuner.setDefaultWidgetPos("beacon", "BeaconPowerButton:1",  93,  31);
        ScreenWidgetTuner.setDefaultWidgetPos("beacon", "BeaconPowerButton:2",  64,  59);
        ScreenWidgetTuner.setDefaultWidgetPos("beacon", "BeaconPowerButton:3",  93,  59);
        ScreenWidgetTuner.setDefaultWidgetPos("beacon", "BeaconPowerButton:4",  79,  87);
        ScreenWidgetTuner.setDefaultWidgetPos("beacon", "BeaconPowerButton:5", 196,  59);
        ScreenWidgetTuner.setDefaultWidgetPos("beacon", "BeaconUpgradePowerButton:0", 168,  47);
        ScreenWidgetTuner.setDefaultWidgetPos("beacon", "BeaconConfirmButton:0", 201, 129);
        ScreenWidgetTuner.setDefaultWidgetPos("beacon", "BeaconCancelButton:0", 229, 129);
        ScreenWidgetTuner.registerAnchor("beacon", "primary_label",  62,  10);
        ScreenWidgetTuner.registerAnchor("beacon", "secondary_label", 169,  10);
    }
}
