package kingdom.smp.inventory;

import kingdom.smp.client.ScreenWidgetTuner;

/**
 * Layout for the Ironhold BlastFurnace screen reskin. Generated by scripts/gen_gui_reskins.py.
 *
 * <p>Source texture blast_furnace_main.png (366×360) is blit-scaled to 280×275 in-game.
 *
 * <p>Widget + label defaults below are baked in from F4-tuned in-game sessions. To update them,
 * tune in-game, hit P, copy values into scripts/gen_gui_reskins.py SPECS for "blast_furnace", regenerate.
 */
public final class BlastFurnaceLayout {
    private BlastFurnaceLayout() {}

    public static final int MAIN_W = 280;
    public static final int MAIN_H = 275;
    public static final int SRC_W  = 366;
    public static final int SRC_H  = 360;

    /** Container-side slot positions (in slot-index order). */
    public static final int[][] CONTAINER_SLOTS = new int[][] {
        {  90,  30 },  // input
        {  90,  80 },  // fuel
        { 180,  55 },  // output
    };

    /** 3×9 main inventory top-left. */
    public static final int INV_X = 24;
    public static final int INV_Y = 154;
    public static final int HOTBAR_Y = 226;
    public static final int INV_COL_STEP = 26;
    public static final int INV_ROW_STEP = 22;

    /** Static-init block registers widget + label defaults and anchor origins so they apply on first screen open. */
    static {
        // (no widget defaults baked in yet — tune in-game with F4 then bake)
    }
}
