package kingdom.smp.inventory;

import kingdom.smp.client.ScreenWidgetTuner;

/**
 * Layout for the Ironhold BrewingStand screen reskin. Generated by scripts/gen_gui_reskins.py.
 *
 * <p>Source texture brewing_stand_main.png (1106×1115) is blit-scaled to 280×282 in-game.
 *
 * <p>Widget + label defaults below are baked in from F4-tuned in-game sessions. To update them,
 * tune in-game, hit P, copy values into scripts/gen_gui_reskins.py SPECS for "brewing_stand", regenerate.
 */
public final class BrewingStandLayout {
    private BrewingStandLayout() {}

    public static final int MAIN_W = 280;
    public static final int MAIN_H = 282;
    public static final int SRC_W  = 1106;
    public static final int SRC_H  = 1115;

    /** Container-side slot positions (in slot-index order). */
    public static final int[][] CONTAINER_SLOTS = new int[][] {
        { 104,  95 },  // bottle0
        { 144, 106 },  // bottle1
        { 183,  95 },  // bottle2
        { 145,  41 },  // ingredient
        {  46,  41 },  // fuel
    };

    /** 3×9 main inventory top-left. */
    public static final int INV_X = 26;
    public static final int INV_Y = 147;
    public static final int HOTBAR_Y = 236;
    public static final int INV_COL_STEP = 26;
    public static final int INV_ROW_STEP = 26;

    /** Static-init block registers widget + label defaults and anchor origins so they apply on first screen open. */
    static {
        // (no widget defaults baked in yet — tune in-game with F4 then bake)
        ScreenWidgetTuner.setDefaultLabelPos("brewing_stand", 0, 103,  24);  // title_label
        ScreenWidgetTuner.setDefaultLabelPos("brewing_stand", 1,  26, 125);  // inv_label
    }
}
