package kingdom.smp.inventory;

import kingdom.smp.client.ScreenWidgetTuner;

/**
 * Layout for the Ironhold Dispenser screen reskin. Generated by scripts/gen_gui_reskins.py.
 *
 * <p>Source texture dispenser_main.png (1106×1115) is blit-scaled to 280×282 in-game.
 *
 * <p>Widget + label defaults below are baked in from F4-tuned in-game sessions. To update them,
 * tune in-game, hit P, copy values into scripts/gen_gui_reskins.py SPECS for "dispenser", regenerate.
 */
public final class DispenserLayout {
    private DispenserLayout() {}

    public static final int MAIN_W = 280;
    public static final int MAIN_H = 282;
    public static final int SRC_W  = 1106;
    public static final int SRC_H  = 1115;

    /** Container-side slot positions (in slot-index order). */
    public static final int[][] CONTAINER_SLOTS = new int[][] {
        { 110,  30 },  // grid0
        { 132,  30 },  // grid1
        { 154,  30 },  // grid2
        { 110,  52 },  // grid3
        { 132,  52 },  // grid4
        { 154,  52 },  // grid5
        { 110,  74 },  // grid6
        { 132,  74 },  // grid7
        { 154,  74 },  // grid8
    };

    /** 3×9 main inventory top-left. */
    public static final int INV_X = 24;
    public static final int INV_Y = 160;
    public static final int HOTBAR_Y = 232;
    public static final int INV_COL_STEP = 26;
    public static final int INV_ROW_STEP = 22;

    /** Static-init block registers widget + label defaults and anchor origins so they apply on first screen open. */
    static {
        // (no widget defaults baked in yet — tune in-game with F4 then bake)
    }
}
