package kingdom.smp.inventory;

import kingdom.smp.client.ScreenWidgetTuner;

/**
 * Layout for the Ironhold Hopper screen reskin. Generated by scripts/gen_gui_reskins.py.
 *
 * <p>Source texture hopper_main.png (1221×1109) is blit-scaled to 290×263 in-game.
 *
 * <p>Widget + label defaults below are baked in from F4-tuned in-game sessions. To update them,
 * tune in-game, hit P, copy values into scripts/gen_gui_reskins.py SPECS for "hopper", regenerate.
 */
public final class HopperLayout {
    private HopperLayout() {}

    public static final int MAIN_W = 290;
    public static final int MAIN_H = 263;
    public static final int SRC_W  = 1221;
    public static final int SRC_H  = 1109;

    /** Container-side slot positions (in slot-index order). */
    public static final int[][] CONTAINER_SLOTS = new int[][] {
        {  83,  48 },  // hop0
        { 109,  48 },  // hop1
        { 135,  48 },  // hop2
        { 161,  48 },  // hop3
        { 187,  48 },  // hop4
    };

    /** 3×9 main inventory top-left. */
    public static final int INV_X = 32;
    public static final int INV_Y = 101;
    public static final int HOTBAR_Y = 203;
    public static final int INV_COL_STEP = 26;
    public static final int INV_ROW_STEP = 27;

    /** Static-init block registers widget + label defaults and anchor origins so they apply on first screen open. */
    static {
        // (no widget defaults baked in yet — tune in-game with F4 then bake)
        ScreenWidgetTuner.setDefaultLabelPos("hopper", 0, 115,  27);  // title_label
        ScreenWidgetTuner.setDefaultLabelPos("hopper", 1,  28,  79);  // inv_label
    }
}
