package kingdom.smp.inventory;

import kingdom.smp.client.ScreenWidgetTuner;

/**
 * Layout for the Ironhold Shulker screen reskin. Generated by scripts/gen_gui_reskins.py.
 *
 * <p>Source texture shulker_main.png (1071×984) is blit-scaled to 315×290 in-game.
 *
 * <p>Widget + label defaults below are baked in from F4-tuned in-game sessions. To update them,
 * tune in-game, hit P, copy values into scripts/gen_gui_reskins.py SPECS for "shulker", regenerate.
 */
public final class ShulkerLayout {
    private ShulkerLayout() {}

    public static final int MAIN_W = 315;
    public static final int MAIN_H = 290;
    public static final int SRC_W  = 1071;
    public static final int SRC_H  = 984;

    /** Container-side slot positions (in slot-index order). */
    public static final int[][] CONTAINER_SLOTS = new int[][] {
        {  35,  42 },  // sh0
        {  63,  42 },  // sh1
        {  91,  42 },  // sh2
        { 119,  42 },  // sh3
        { 147,  42 },  // sh4
        { 175,  42 },  // sh5
        { 203,  42 },  // sh6
        { 231,  42 },  // sh7
        { 259,  42 },  // sh8
        {  35,  70 },  // sh9
        {  63,  70 },  // sh10
        {  91,  70 },  // sh11
        { 119,  70 },  // sh12
        { 147,  70 },  // sh13
        { 175,  70 },  // sh14
        { 203,  70 },  // sh15
        { 231,  70 },  // sh16
        { 259,  70 },  // sh17
        {  35,  98 },  // sh18
        {  63,  98 },  // sh19
        {  91,  98 },  // sh20
        { 119,  98 },  // sh21
        { 147,  98 },  // sh22
        { 175,  98 },  // sh23
        { 203,  98 },  // sh24
        { 231,  98 },  // sh25
        { 259,  98 },  // sh26
    };

    /** 3×9 main inventory top-left. */
    public static final int INV_X = 35;
    public static final int INV_Y = 144;
    public static final int HOTBAR_Y = 241;
    public static final int INV_COL_STEP = 28;
    public static final int INV_ROW_STEP = 28;

    /** Static-init block registers widget + label defaults and anchor origins so they apply on first screen open. */
    static {
        // (no widget defaults baked in yet — tune in-game with F4 then bake)
    }
}
