package kingdom.smp.inventory;

import kingdom.smp.client.ScreenWidgetTuner;

/**
 * Layout for the Ironhold Smithing screen reskin. Generated by scripts/gen_gui_reskins.py.
 *
 * <p>Source texture smithing_main.png (1150×1150) is blit-scaled to 280×280 in-game.
 *
 * <p>Widget + label defaults below are baked in from F4-tuned in-game sessions. To update them,
 * tune in-game, hit P, copy values into scripts/gen_gui_reskins.py SPECS for "smithing", regenerate.
 */
public final class SmithingLayout {
    private SmithingLayout() {}

    public static final int MAIN_W = 280;
    public static final int MAIN_H = 280;
    public static final int SRC_W  = 1150;
    public static final int SRC_H  = 1150;

    /** Container-side slot positions (in slot-index order). */
    public static final int[][] CONTAINER_SLOTS = new int[][] {
        {  30,  50 },  // template
        {  60,  50 },  // base
        {  90,  50 },  // addition
        { 200,  50 },  // out
    };

    /** 3×9 main inventory top-left. */
    public static final int INV_X = 24;
    public static final int INV_Y = 158;
    public static final int HOTBAR_Y = 230;
    public static final int INV_COL_STEP = 26;
    public static final int INV_ROW_STEP = 22;

    /** Static-init block registers widget + label defaults and anchor origins so they apply on first screen open. */
    static {
        // (no widget defaults baked in yet — tune in-game with F4 then bake)
    }
}
