package kingdom.smp.inventory;

import kingdom.smp.client.ScreenWidgetTuner;

/**
 * Layout for the Ironhold Villager screen reskin. Generated by scripts/gen_gui_reskins.py.
 *
 * <p>Source texture villager_main.png (1192×871) is blit-scaled to 320×234 in-game.
 *
 * <p>Widget + label defaults below are baked in from F4-tuned in-game sessions. To update them,
 * tune in-game, hit P, copy values into scripts/gen_gui_reskins.py SPECS for "villager", regenerate.
 */
public final class VillagerLayout {
    private VillagerLayout() {}

    public static final int MAIN_W = 320;
    public static final int MAIN_H = 234;
    public static final int SRC_W  = 1192;
    public static final int SRC_H  = 871;

    /** Container-side slot positions (in slot-index order). */
    public static final int[][] CONTAINER_SLOTS = new int[][] {
        { 142,  50 },  // trade_in1
        { 175,  50 },  // trade_in2
        { 245,  50 },  // out
    };

    /** 3×9 main inventory top-left. */
    public static final int INV_X = 115;
    public static final int INV_Y = 105;
    public static final int HOTBAR_Y = 178;
    public static final int INV_COL_STEP = 22;
    public static final int INV_ROW_STEP = 22;

    /** Static-init block registers widget + label defaults and anchor origins so they apply on first screen open. */
    static {
        // (no widget defaults baked in yet — tune in-game with F4 then bake)
    }
}
