package kingdom.smp.client.entity;

import com.mojang.blaze3d.vertex.PoseStack;
import kingdom.smp.Ironhold;
import net.minecraft.client.model.ArmedModel;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.resources.Identifier;
import net.minecraft.util.Mth;
import net.minecraft.world.entity.HumanoidArm;

/**
 * Foreman Dunstan's stocky miner model.
 * GENERATED by scripts/import_miner_dunstan.py from
 * art/blockbench/miner_dunstan/miner_dunstan.bbmodel; edit the bbmodel
 * in Blockbench and re-run the importer, do not edit this file.
 */
public class MinerDunstanModel extends EntityModel<MinerDunstanRenderState>
    implements ArmedModel<MinerDunstanRenderState> {

    public static final ModelLayerLocation LAYER_LOCATION = new ModelLayerLocation(
        Identifier.fromNamespaceAndPath(Ironhold.MODID, "miner_dunstan"), "main");

    /** Rest pose of the left arm, baked in Blockbench. */
    private static final float LEFT_ARM_POSE_X = -0.48F;

    private final ModelPart head;
    private final ModelPart body;
    private final ModelPart rightArm;
    private final ModelPart leftArm;
    private final ModelPart rightLeg;
    private final ModelPart leftLeg;

    public MinerDunstanModel(ModelPart root) {
        super(root);
        this.head = root.getChild("head");
        this.body = root.getChild("body");
        this.rightArm = root.getChild("right_arm");
        this.leftArm = root.getChild("left_arm");
        this.rightLeg = root.getChild("right_leg");
        this.leftLeg = root.getChild("left_leg");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();

        PartDefinition head = root.addOrReplaceChild("head",
            CubeListBuilder.create()
                .texOffs(0, 0)
                .mirror(true)
                .addBox(-4.0F, -8.0F, -4.0F, 8.0F, 8.0F, 8.0F, CubeDeformation.NONE)
                .texOffs(34, 0)
                .mirror(true)
                .addBox(-1.0F, -3.0F, -6.0F, 2.0F, 3.0F, 2.0F, CubeDeformation.NONE)
                .texOffs(58, 0)
                .mirror(true)
                .addBox(-4.3F, -9.0F, -5.0F, 8.6F, 3.0F, 10.0F, CubeDeformation.NONE)
                .texOffs(64, 2)
                .mirror(true)
                .addBox(-3.3F, -10.0F, -4.0F, 6.6F, 1.0F, 8.0F, CubeDeformation.NONE)
                .texOffs(2, 17)
                .mirror(true)
                .addBox(-5.0F, -6.0F, -6.0F, 10.0F, 1.0F, 12.0F, CubeDeformation.NONE)
                .texOffs(54, 18)
                .mirror(true)
                .addBox(-1.3F, -8.6F, -6.3F, 2.6F, 2.6F, 1.3F, CubeDeformation.NONE)
                .texOffs(53, 19)
                .mirror(true)
                .addBox(-2.0F, -6.0F, -6.7F, 4.0F, 1.1F, 0.7F, CubeDeformation.NONE)
                .texOffs(54, 19)
                .mirror(true)
                .addBox(-1.9F, -9.0F, -6.1F, 3.8F, 4.0F, 0.7F, CubeDeformation.NONE)
                .texOffs(69, 18)
                .mirror(true)
                .addBox(-1.0F, -8.0F, -6.5F, 2.0F, 2.0F, 0.2F, CubeDeformation.NONE)
            , PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition body = root.addOrReplaceChild("body",
            CubeListBuilder.create()
                .texOffs(77, 17)
                .mirror(true)
                .addBox(-4.0F, 0.0F, -2.0F, 8.0F, 12.0F, 4.0F, CubeDeformation.NONE)
            , PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition rightArm = root.addOrReplaceChild("right_arm",
            CubeListBuilder.create()
                .texOffs(73, 34)
                .mirror(true)
                .addBox(-3.0F, -2.0F, -2.0F, 4.0F, 7.0F, 4.0F, CubeDeformation.NONE)
                .texOffs(90, 34)
                .mirror(true)
                .addBox(-3.0F, 5.0F, -2.0F, 4.0F, 2.0F, 4.0F, CubeDeformation.NONE)
                .texOffs(107, 34)
                .mirror(true)
                .addBox(-3.0F, 7.0F, -2.0F, 4.0F, 3.0F, 4.0F, new CubeDeformation(0.10F))
            , PartPose.offset(-5.0F, 2.0F, 0.0F));

        PartDefinition leftArm = root.addOrReplaceChild("left_arm",
            CubeListBuilder.create()
                .texOffs(0, 46)
                .mirror(true)
                .addBox(-1.0F, -2.0F, -2.0F, 4.0F, 7.0F, 4.0F, CubeDeformation.NONE)
                .texOffs(17, 46)
                .mirror(true)
                .addBox(-1.0F, 5.0F, -2.0F, 4.0F, 2.0F, 4.0F, CubeDeformation.NONE)
                .texOffs(34, 46)
                .mirror(true)
                .addBox(-1.0F, 7.0F, -2.0F, 4.0F, 3.0F, 4.0F, new CubeDeformation(0.10F))
            , PartPose.offsetAndRotation(5.0F, 2.0F, 0.0F, -0.48F, -0.0F, 0.0F));

        PartDefinition rightLeg = root.addOrReplaceChild("right_leg",
            CubeListBuilder.create()
                .texOffs(51, 46)
                .mirror(true)
                .addBox(-2.0F, 0.0F, -2.0F, 4.0F, 6.0F, 4.0F, CubeDeformation.NONE)
                .texOffs(88, 72)
                .mirror(true)
                .addBox(-2.1F, 9.9F, -3.5F, 4.1F, 2.1F, 5.7F, CubeDeformation.NONE)
                .texOffs(88, 67)
                .mirror(true)
                .addBox(-2.1F, 6.0F, -2.5F, 4.1F, 3.9F, 4.7F, CubeDeformation.NONE)
            , PartPose.offset(-2.0F, 12.0F, 0.0F));

        PartDefinition leftLeg = root.addOrReplaceChild("left_leg",
            CubeListBuilder.create()
                .texOffs(106, 46)
                .mirror(true)
                .addBox(-2.0F, 0.0F, -2.0F, 4.0F, 6.0F, 4.0F, CubeDeformation.NONE)
                .texOffs(88, 56)
                .mirror(true)
                .addBox(-2.0F, 6.0F, -2.5F, 4.1F, 3.9F, 4.7F, CubeDeformation.NONE)
                .texOffs(87, 46)
                .mirror(true)
                .addBox(-2.0F, 9.9F, -3.5F, 4.1F, 2.1F, 5.7F, CubeDeformation.NONE)
            , PartPose.offset(2.0F, 12.0F, 0.0F));

        return LayerDefinition.create(mesh, 128, 128);
    }

    @Override
    public void translateToHand(
        MinerDunstanRenderState state,
        HumanoidArm arm,
        PoseStack poseStack
    ) {
        ModelPart armPart = arm == HumanoidArm.RIGHT ? this.rightArm : this.leftArm;
        armPart.translateAndRotate(poseStack);
    }

    @Override
    public void setupAnim(MinerDunstanRenderState state) {
        super.setupAnim(state);
        float t = state.ageInTicks;
        float walkSpeed = state.walkAnimationSpeed;
        float walkPos = state.walkAnimationPos;

        this.head.yRot = state.yRot * Mth.DEG_TO_RAD;
        this.head.xRot = state.xRot * Mth.DEG_TO_RAD;

        float swing = Mth.cos(walkPos * 0.6662F) * 1.2F * walkSpeed;
        this.rightLeg.xRot = swing;
        this.leftLeg.xRot = -swing;
        this.leftArm.xRot = LEFT_ARM_POSE_X + swing * 0.65F;

        // Keep the tool-bearing arm controlled and weighty.
        this.rightArm.xRot = -0.30F - swing * 0.18F + Mth.sin(t * 0.04F) * 0.025F;
        this.rightArm.yRot = -0.08F;
        this.rightArm.zRot = 0.16F;
        this.leftArm.zRot = -0.06F;
        this.body.zRot = Mth.sin(walkPos * 0.6662F) * 0.025F * walkSpeed;
    }
}
