package kingdom.smp.client.entity;

import kingdom.smp.Ironhold;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.client.renderer.entity.state.LivingEntityRenderState;
import net.minecraft.resources.Identifier;
import net.minecraft.util.Mth;

/**
 * Doctor Corvus — wide-brim-hatted, beaked plague doctor (humanoid).
 * GENERATED by scripts/gen_plague_doctor.py — edit the spec there, not here.
 * Texture 128x128, box-uv. Pivots follow the IllagerModel convention
 * (head/body share pivot at upper chest; head extends -Y).
 */
public class PlagueDoctorModel extends EntityModel<LivingEntityRenderState> {

    public static final ModelLayerLocation LAYER_LOCATION = new ModelLayerLocation(
        Identifier.fromNamespaceAndPath(Ironhold.MODID, "plague_doctor"), "main");

    private final ModelPart head;
    private final ModelPart body;
    private final ModelPart right_arm;
    private final ModelPart left_arm;
    private final ModelPart right_leg;
    private final ModelPart left_leg;

    public PlagueDoctorModel(ModelPart root) {
        super(root);
        this.head = root.getChild("head");
        this.body = root.getChild("body");
        this.right_arm = root.getChild("right_arm");
        this.left_arm = root.getChild("left_arm");
        this.right_leg = root.getChild("right_leg");
        this.left_leg = root.getChild("left_leg");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();

        root.addOrReplaceChild("head",
            CubeListBuilder.create()
                .texOffs(0, 0)
                .addBox(-4.0F, -8.0F, -4.0F, 8, 8, 8, CubeDeformation.NONE)
                .texOffs(33, 0)
                .addBox(-1.0F, -4.0F, -8.0F, 2, 3, 4, CubeDeformation.NONE)
                .texOffs(46, 0)
                .addBox(-7.0F, -9.0F, -7.0F, 14, 1, 14, CubeDeformation.NONE)
                .texOffs(0, 17)
                .addBox(-4.5F, -13.0F, -4.5F, 9, 4, 9, CubeDeformation.NONE),
            PartPose.offset(0.0F, 0.0F, 0.0F));

        root.addOrReplaceChild("body",
            CubeListBuilder.create()
                .texOffs(37, 17)
                .addBox(-4.0F, 0.0F, -2.0F, 8, 12, 4, CubeDeformation.NONE)
                .texOffs(62, 17)
                .addBox(-5.5F, 0.0F, -3.5F, 11, 6, 7, CubeDeformation.NONE)
                .texOffs(99, 17)
                .addBox(-4.5F, 8.5F, -2.5F, 9, 2, 5, CubeDeformation.NONE)
                .texOffs(0, 34)
                .addBox(2.5F, 9.5F, -3.0F, 1, 3, 1, CubeDeformation.NONE)
                .texOffs(5, 34)
                .addBox(-3.5F, 9.5F, -3.0F, 1, 3, 1, CubeDeformation.NONE)
                .texOffs(10, 34)
                .addBox(3.0F, 9.0F, -1.0F, 2, 4, 3, CubeDeformation.NONE),
            PartPose.offset(0.0F, 0.0F, 0.0F));

        root.addOrReplaceChild("right_arm",
            CubeListBuilder.create()
                .texOffs(21, 34)
                .addBox(-3.0F, -2.0F, -2.0F, 4, 12, 4, CubeDeformation.NONE)
                .texOffs(38, 34)
                .addBox(-3.0F, 8.0F, -2.0F, 4, 2, 4, new CubeDeformation(0.35F)),
            PartPose.offset(-5.0F, 2.0F, 0.0F));

        root.addOrReplaceChild("left_arm",
            CubeListBuilder.create()
                .texOffs(55, 34)
                .addBox(-1.0F, -2.0F, -2.0F, 4, 12, 4, CubeDeformation.NONE)
                .texOffs(72, 34)
                .addBox(-1.0F, 8.0F, -2.0F, 4, 2, 4, new CubeDeformation(0.35F)),
            PartPose.offset(5.0F, 2.0F, 0.0F));

        root.addOrReplaceChild("right_leg",
            CubeListBuilder.create()
                .texOffs(89, 34)
                .addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4, CubeDeformation.NONE)
                .texOffs(106, 34)
                .addBox(-2.0F, 9.0F, -3.0F, 4, 3, 5, CubeDeformation.NONE),
            PartPose.offset(-2.0F, 12.0F, 0.0F));

        root.addOrReplaceChild("left_leg",
            CubeListBuilder.create()
                .texOffs(0, 51)
                .addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4, CubeDeformation.NONE)
                .texOffs(17, 51)
                .addBox(-2.0F, 9.0F, -3.0F, 4, 3, 5, CubeDeformation.NONE),
            PartPose.offset(2.0F, 12.0F, 0.0F));

        return LayerDefinition.create(mesh, 128, 128);
    }

    @Override
    public void setupAnim(LivingEntityRenderState state) {
        super.setupAnim(state);
        float t = state.ageInTicks;
        float walkSpeed = state.walkAnimationSpeed;
        float walkPos = state.walkAnimationPos;

        // Head tracks the player.
        this.head.yRot = state.yRot * Mth.DEG_TO_RAD;
        this.head.xRot = state.xRot * Mth.DEG_TO_RAD;

        // Four-beat walk gait.
        float swing = Mth.cos(walkPos * 0.6662F) * 1.2F * walkSpeed;
        this.right_leg.xRot = swing;
        this.left_leg.xRot = -swing;
        this.right_arm.xRot = -swing * 0.6F;
        this.left_arm.xRot = swing * 0.6F;

        // Slow, ominous idle sway.
        float sway = Mth.sin(t * 0.045F) * 0.05F;
        this.right_arm.zRot = 0.08F + sway;
        this.left_arm.zRot = -0.08F - sway;
        this.body.yRot = Mth.sin(t * 0.03F) * 0.03F;
    }
}
